# Site settings
title: KPI Framework
description: Step-by-step guide to my project
baseurl: ""      # leave empty if using user.github.io/repo format
url: "https://kalungzmh.github.io/KPI-Framework/"  # replace with your GitHub Pages URL

# Jekyll theme
theme: midnight

# Author info (optional)
author:
  name: Kalun He
  email: Kalun@gedeeldezorgMH.nl

# Navigation / sidebar
nav:
  - Home: index.md

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM   # GitHub-Flavored Markdown
